### ISSUE TITLE
Top-level navigation does not work in Firefox

### ISSUE THREAD

**Issue by audreyt** [twreporter/twreporter-react#141] opened 2016-01-05 16:15 UTC
On homepage, clicking any of the top-level categories results in:

```
TypeError: CSS2Properties doesn't have an indexed property setter for '0'
x.setValueForStyles()
 main.js:76
r.measure/a()
 main.js:1
b.Mixin._updateDOMProperties()
 main.js:78
```

Chrome and Safari works just fine.

**Comment by nickhsine** [comment] 2016-01-05 17:34
@audreyt @hcchien 
This problem seems to be caused by ```react-burger-menu```.
Will remove burger menu first to make firefox work.

**Comment by nickhsine** [comment] 2016-01-08 10:50
https://github.com/twreporter/twreporter-react/pull/144 temporarily fixed by removing ```react-burger-menu```

**Closed by nickhsine** 2016-01-08 10:50 UTC

**Comment by stanleycyang** [comment] 2016-03-08 16:08
Why is react-burger-menu an issue? I don't follow the train of logic
